import { PATH_API } from './path';

export const QUERY_KEY = {
  SIGN_IN: PATH_API.SIGN_IN,
  SIGN_UP: PATH_API.SIGN_UP,
  CAPSULE_BOX: PATH_API.CAPSULE_BOX,
  // user
  USER_INFO: PATH_API.USER_INFO,
  USER_RESIGN: PATH_API.USER_RESIGN,
  USER_PATCH: PATH_API.USER_PATCH,
  // capsule
  MAKE_CAPSULE_BOX: PATH_API.MAKE_CAPSULE_BOX,
  MAKE_CAPSULE: PATH_API.MAKE_CAPSULE,
  CAPSULE_LIST: PATH_API.CAPSULE_LIST,
  CAPSULE_DETAIL: PATH_API.CAPSULE_DETAIL,
  // notice
  NOTICE: PATH_API.NOTICE,
  // history
  HISTORY: PATH_API.HISTORY,
  // inquiry
  INQUIRY: PATH_API.INQUIRY,
};
