import { PATH_API } from './path';

export const QUERY_KEY = {
  SIGN_IN: PATH_API.SIGN_IN,
  SIGN_UP: PATH_API.SIGN_UP,
  CAPSULE_BOX: PATH_API.CAPSULE_BOX,
  USER_INFO: PATH_API.USER_INFO,
  MAKE_CAPSULE_BOX: PATH_API.MAKE_CAPSULE_BOX,
  MAKE_CAPSULE: PATH_API.MAKE_CAPSULE,
  // notice
  NOTICE: PATH_API.NOTICE,
  // history
  HISTORY: PATH_API.HISTORY,
  // inquiry
  INQUIRY: PATH_API.INQUIRY,
};
